config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root "pages#home"
  
  get "ici", to: "pages#about"
  get "hihé", to: "pages#hihi", as: :hihi

  get "restaurants/top", to: "restaurants#top"
  get "restaurants", to: "restaurants#index"
  get "restaurants/new", to: "restaurants#new", as: :new_restaurant
  post "restaurants", to: "restaurants#create"
  get "restaurants/:id", to: "restaurants#show", as: :restaurant
  get "restaurants/:id/edit", to: "restaurants#edit", as: :edit_restaurant
  patch "restaurants/:id", to: "restaurants#update"
  delete "restaurants/:id", to: "restaurants#destroy"
  

  get "up" => "rails/health#show", as: :rails_health_check
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
   
    def about 
    end

    def hihi
        @membrs = ["thanh", "dimitri", "germain", "damien", "julien", "jean", "pierre"]
         
        if params[:fuckers]
            @membrs = @membrs.select { |m| m.start_with?(params[:fuckers]) }
            
        end
    end   

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    #before_action :set_restaurant, only: [:show, :edit, :update, :destroy] 
    
    before_action :set_restaurant, only: %i[show edit update destroy] # => fait la même chose que la ligne 2
    
    def top
        #@restaurants = Restaurant.where(note: [4,5])   # ici on choisi les notes de façon exclusives, 'égale à 4 ou à 5'
        @restaurants = Restaurant.where("note > 2")     # ici on crée une condition 'supérieure à 2'
    end
    
    def index
        @restaurants = Restaurant.all
    end

    def show 
    end

    def new
        @restaurant = Restaurant.new 
    end

    def create
        @restaurant = Restaurant.new(restaurant_params)
        @restaurant.save
        redirect_to restaurant_path(@restaurant), notice: "Restaurant was successfully created."
    end
      
    def edit
    end

    def update
        @restaurant.update(restaurant_params)
        redirect_to restaurant_path(@restaurant)
      end

      def destroy
        @restaurant.destroy
        redirect_to restaurants_path, status: :see_other
      end  

    private
      
    def restaurant_params
        params.require(:restaurant).permit(:nom, :adresse, :note)
    end

    def set_restaurant
        @restaurant = Restaurant.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApplicationTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <p>Now is <%= Time.now %></p>
  </body>
</html>

app/views/pages/about.html.erb
<h1>
    ici les loulous
</h1>

<%= link_to "hihé", hihi_path%>
<%= link_to "ici", ici_path%>
<%= link_to "restaurants", restaurants_path%>
<%= link_to "restaurants_new", new_restaurant_path%>

app/views/pages/hihi.html.erb
<h1>Formulaire</h1>

<form action="/hihé" method="get">
  <input 
        type="text" 
        name="fuckers" 
        value="<%= params[:fuckers] %>" 
        placeholder="Whooo arh u loop king for?"
    >

  <input type="submit">
</form>

<h2>Mites pour team</h2>
<ol>
  <% @membrs.each do |m| %>
    <li><%= m.capitalize %></li>
  <% end %>
</ol>

<%= link_to "hihé", hihi_path%>
<%= link_to "ici", ici_path%>
<%= link_to "restaurants", restaurants_path%>
<%= link_to "restaurants_new", new_restaurant_path%>

app/views/pages/home.html.erb
<h1>HOME PAGE</h1>
<div data-controller="email">
    <input name="e-mail" id="e-mail" value="paul@gmail.com" />
</div>


<%= link_to "hihé", hihi_path%>
<%= link_to "ici", ici_path%>
<%= link_to "restaurants", restaurants_path%>
<%= link_to "restaurants_new", new_restaurant_path%>

app/views/restaurants/_form.html.erb
<h1>Formulaire avec form_for</h1>

<%= form_with model: restaurant do |f| %>
  <%= f.label :nom %>
  <%= f.text_field :nom %>
  <%= f.label :adresse %>
  <%= f.text_field :adresse %>
  <%= f.label :note %>
  <%= f.number_field :note %>
  <%= f.submit %>
<% end %>

<h1>Formulaire avec simple_form_for</h1>

<%= simple_form_for(restaurant) do |f| %>
  <%= f.input :nom %>
  <%= f.input :adresse %>
  <%= f.input :note %>
  <%= f.submit %>
<% end %>

 <%= link_to "Annuler", restaurants_path%> 

app/views/restaurants/_restaurant.html.erb
<h2><%= restaurant.nom %></h2>
<p>Son Adresse : <%= restaurant.adresse %></p>
<p>Sa note : <%= restaurant.note %>/5</p>

app/views/restaurants/edit.html.erb
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<h1>Mes Restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
   <li><%=link_to restaurant.nom, restaurant_path(restaurant)  %></li>
  <% end %>
</ul>

<%= link_to "hihé", hihi_path%>
<%= link_to "ici", ici_path%>
<%= link_to "restaurants", restaurants_path%>
<%= link_to "restaurants_new", new_restaurant_path%>

app/views/restaurants/new.html.erb
<%= render "form", restaurant: @restaurant %>



<%= link_to "hihé", hihi_path%>
<%= link_to "ici", ici_path%>
<%= link_to "restaurants", restaurants_path%>
<%= link_to "restaurants_new", new_restaurant_path%>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.nom %></h2>
<p>Son Adresse : <%= @restaurant.adresse %></p>
<p>Sa note : <%= @restaurant.note %>/5</p>

<%= link_to "Delete",
  restaurant_path(@restaurant),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>

<%= link_to "hihé", hihi_path%>
<%= link_to "ici", ici_path%>
<%= link_to "restaurants", restaurants_path%>
<%= link_to "restaurants_new", new_restaurant_path%>
<%= link_to "restaurants_edit", edit_restaurant_path%>

app/views/restaurants/top.html.erb
<h1>5 Stars Restaurants</h1>

<div id="restaurants">

  <% @restaurants.each do |restaurant| %>
    <%= render restaurant %>
    <p>
      <%= link_to "Show this restaurant", restaurant %>
    </p>
  <% end %>
</div>